### ISSUE TITLE
Format: Empty second line in query template string marked as error but not autofixed

### ISSUE THREAD

**Issue by karlhorky** [gajus/eslint-plugin-sql#10]
The following code will generate an error because of the second blank line, but the error will not be autofixed:

```js
  const a = await sql`

SELECT
  ${'foo'}
FROM
  ${'bar'}
`;
```

**Comment by MatthewMaclean** [comment]
It's difficult to use this library when fix breaks the lint.

**Comment by Stuk** [comment]
Encountering this too. I think it's the duplicate prefixing of `\n` on

https://github.com/gajus/eslint-plugin-sql/blob/4537d7fcc3f7d28a45b63b1b56bc6eb9625cd30c/src/rules/format.ts#L50-L55

and

https://github.com/gajus/eslint-plugin-sql/blob/4537d7fcc3f7d28a45b63b1b56bc6eb9625cd30c/src/rules/format.ts#L75-L81
