### ISSUE TITLE
Option for `format` rule for matching indentation?

### ISSUE THREAD

**Issue by karlhorky** [gajus/eslint-plugin-sql#9]
Hi @gajus ! First of all, thanks for your great work in the PostgreSQL + JS ecosystem, really cool stuff that you're doing always with Slonik and everything! 💯

I was wondering if it would be possible to have an option for the `format` rule to adjust the formatted string . Here's an example of code that could be improved because of this:

```js
async function a() {
  if (condition) {
    // ...some code...
    if (anotherCondition) {
      const b = await sql`
SELECT
  ${'foo'}
FROM
  ${'bar'}
`;
    }
  }
}
```

How this code could look:

```js
async function a() {
  if (condition) {
    // ...some code...
    if (anotherCondition) {
      const b = await sql`
        SELECT
          ${'foo'}
        FROM
          ${'bar'}
      `;
    }
  }
}
```

Since SQL is not whitespace-sensitive I am assuming this would not be a destructive action.

If this option would be something conceivable to add to the plugin, I guess the AST tells us that some information of the starting indentation of the `TaggedTemplateExpression` may be available under the `loc.start.column` object property path:

![Screen Shot 2020-11-19 at 20 15 40](https://user-images.githubusercontent.com/1935696/99712947-0d3c7080-2aa4-11eb-8a40-ba338d740d36.png)

And then splitting the formatted string by `'\n'`, mapping over each line (except the first one) to add spaces:

```js
formatted.map((line, i) => {
  if (i === 0) return line;

  const spaces = context.options[1].spaces || 4;
  const indentation = ' '.repeat(column + spaces);
  return `${indentation}${line}`;
}
```

...and then joining again with `\n`.

What are your thoughts?

**Comment by gajus** [comment]
This would be nice to have, but not something I would personally undertake developing. The implementation complexity vs value ratio just makes it not worth it.

I am closing the issue, but if you / someone else were to work on it and have a sturdy PR, I'd help to review / merge it.

**Comment by karlhorky** [comment]
After digging a bit into it for the description above, it seems like the algorithm / code would be not much more than that quoted above. I can take a look, sure :)

Maybe reopen this one and I'll close it with the PR?

**Comment by karlhorky** [comment]
@gajus ok I've opened #11, this seems to be working (although it still has the existing bug #10).
